# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-11 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(default=None, max_length=64)),
                ('definition', models.CharField(default=None, max_length=250)),
                ('response1', models.CharField(default=None, max_length=64)),
                ('response2', models.CharField(default=None, max_length=64)),
            ],
        ),
    ]
