# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-02 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=None, max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='queries',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AddField(
            model_name='entry',
            name='translation',
            field=models.CharField(blank=True, default=None, max_length=250, null=True),
        ),
    ]
