# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-12 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dict', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='queries',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
